/////////////////////////////////////////////////////////////////////////////////////
//
//    File Name       : MarvellousUnpackerGUI.java
//    Description     : This program implements the GUI for unpacking files that were packed using the Marvellous Packer. 
//                      It reads a packed file, extracts individual files based on stored headers, and saves them separately.
//    Author          : Kartik Ganesh Jare
//    Date            : 24/09/2025
//    
/////////////////////////////////////////////////////////////////////////////////////

package MarvellousPackerUnpacker;

import java.util.*;
import java.io.*;
import javax.swing.*;
import java.awt.event.*;

/////////////////////////////////////////////////////////////////////////////////////
//
//    Class Name      : MarvellousUnpackerGUI
//    Description     : Provides a GUI interface for unpacking files from a packed archive created by Marvellous Packer. 
//                      Uses Swing components for interaction.
//    Author          : Kartik Ganesh Jare
//    Date            : 24/09/2025
//
/////////////////////////////////////////////////////////////////////////////////////

public class MarvellousUnpackerGUI implements ActionListener
{
    private String PackName;
    public JButton button;
    public JFrame frame;
    public JLabel filelable;
    public JTextField filtextfield;
    public JTextArea InfoArea;
    public JScrollPane scrollPane;

    /////////////////////////////////////////////////////////////////////////////////////
    //
    //    Function Name   : MarvellousUnpackerGUI (Constructor)
    //    Description     : Initializes the GUI components, sets layout, 
    //                      and prepares the application window.
    //    Author          : Kartik Ganesh Jare
    //    Date            : 24/09/2025
    //    Prototype       : public MarvellousUnpackerGUI(String Title, int Width, int Height)
    //    Input           : Title (String) - Window title
    //                      Width (int) - Width of window
    //                      Height (int) - Height of window
    //    Output          : None
    //
    /////////////////////////////////////////////////////////////////////////////////////

    public MarvellousUnpackerGUI(String Title, int Width, int Height)
    {
        frame = new JFrame();

        filelable = new JLabel("File Name:");
        filelable.setBounds(40, 40, 140, 30);

        filtextfield = new JTextField();
        filtextfield.setBounds(180, 40, 200, 30);

        button = new JButton("UNPACK");
        button.setBounds(150, 90 , 120, 40);
        button.addActionListener(this);

        InfoArea = new JTextArea();
        InfoArea.setEditable(false);

        scrollPane = new JScrollPane(InfoArea);
        scrollPane.setBounds(20,150,360,250);

        frame.add(filelable);
        frame.add(filtextfield);
        frame.add(button);
        frame.add(scrollPane);

        frame.setLayout(null);
        frame.setTitle(Title);
        frame.setSize(Width, Height);
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /////////////////////////////////////////////////////////////////////////////////////
    //
    //    Function Name   : actionPerformed
    //    Description     : Handles button click event. Retrieves filename 
    //                      from text field and triggers unpacking.
    //    Author          : Kartik Ganesh Jare
    //    Date            : 24/09/2025
    //    Prototype       : public void actionPerformed(ActionEvent aobj)
    //    Input           : ActionEvent aobj - Event generated by button click
    //    Output          : None
    //
    /////////////////////////////////////////////////////////////////////////////////////
    
    public void actionPerformed(ActionEvent aobj)
    {
        PackName = filtextfield.getText().trim();  // ← Correct method

        if(PackName.equals(""))
        {
            JOptionPane.showMessageDialog(frame,"Please enter the packed file name!","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }

        UnpackingActiviy();
    }

    /////////////////////////////////////////////////////////////////////////////////////
    //
    //    Function Name   : UnpackingActiviy
    //    Description     : Opens the packed file, reads headers, extracts 
    //                      files, and writes them to disk. Displays 
    //                      information in the InfoArea.
    //    Author          : Kartik Ganesh Jare
    //    Date            : 24/09/2025
    //    Prototype       : public void UnpackingActiviy()
    //    Input           : None
    //    Output          : None
    //
    /////////////////////////////////////////////////////////////////////////////////////
   
    public void UnpackingActiviy()
    {
        try
        {
            String Header = null;
            File fobjnew = null;
            int FileSize = 0,iRet = 0,iCountFile = 0;

            File fobj = new File(PackName);

            // If packed file is not present
            if(! fobj.exists())
            {
                JOptionPane.showMessageDialog(frame, "Packed file not found!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            InfoArea.setText("Packed file succesfully opened\n");

            FileInputStream fiobj = new FileInputStream(fobj);

            // Buffer to read the header
            byte HeaderBuffer[] = new byte[100]; 

            // Scan the packed file extract the file from it
            while((iRet =fiobj.read(HeaderBuffer,0,100)) != -1)
            {
                // Covnert byte array to string
                Header = new String(HeaderBuffer);

                Header = Header.trim();

                // Tokenize the header into 2 parts
                String Tokens[] = Header.split(" ");
                
                fobjnew = new File(Tokens[0]);

                // Create new file to extract
                fobjnew.createNewFile();
                
                FileSize = Integer.parseInt(Tokens[1]);

                // Create new buffer to store file data
                byte Buffer[] = new byte[FileSize];

                FileOutputStream foobj = new FileOutputStream(fobjnew);

                // Read the data from packed file
                fiobj.read(Buffer,0,FileSize);

                // write the data into etracted file
                foobj.write(Buffer,0,FileSize);

                InfoArea.append("File unpack with name : "+Tokens[0]+" having size  " +FileSize+"\n");

                iCountFile++;

                foobj.close();
            }//End of while

            InfoArea.append("\n-----------------------Statistical Report------------------------------\n");
            InfoArea.append("Total number of file unpacked : "+iCountFile+"\n");
            InfoArea.append("--------------------------------------------\n");
            InfoArea.append("Thank you for using our application\n");

            fiobj.close();    
        }
        catch(Exception eobj)
        {
            JOptionPane.showMessageDialog(frame, "An error occurred during unpacking.\n" + eobj.getMessage(), "Exception", JOptionPane.ERROR_MESSAGE);
        }
    }// Try End
} // End UnpackingActivity  